### ISSUE TITLE
cmd does not register thdat or any application as valid

### ISSUE THREAD

**Issue by FPSvoltage** [thpatch/thtk#47]
Im glad i found this place and i hope to find an answer here. ive been trying to get the toolkit working to no avail and i desperately need help. Ive been reading all the "read me"s i could find but it says that 'thdat' is not recognized as an internal or external command. can someone please tell me whats wrong ? 

it also seems i can only get the .dat file out of games, no ecl or anm or msg

**Comment by ManDude** [comment]
It appears you don't have much experience with using the command prompt. Let me explain.

When you open the console, it will show a directory (which I'll refer here as the "working directory"). When you type and attempt to launch "thdat", it will search for thdat.exe in the working directory.

This means that, to use thdat.exe located in the C:\crap\garbage directory, and your current directory is something like C:\trash, you need to cd into C:\crap\garbage by typing just that: `cd C:\crap\garbage`
CD changes your current working directory. Now, typing thdat will launch thdat properly. Note that you can drag a file from Windows Explorer to the CMD prompt to make it automatically pop out the FULL PATH to the executable which doesn't care about your working directory (meaning it can be C:\trash as long as you type `C:\crap\garbage\thdat.exe` instead of just thdat).

NOTE: thdat extracts the contents of the .dat file to the working directory. I recommend making a folder where you want to put the files in and CD'ing to it and running thdat from there.

**Comment by FPSvoltage** [comment]
Oh right i completely forgot about changing directory ! i feel dumb.. thank you for helping me !

**Comment by ManDude** [comment]
yw
